name: 🍎 macOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: "macos-14"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          #- name: Editor (target=editor, tests=yes)
          #   cache-name: macos-editor
          #   target: editor
          #   tests: true
          #   bin: "./bin/godot.macos.editor.x86_64"
          - name: Editor (target=editor, tests=yes, arch=arm64, mono=yes)
            cache-name: macos-editor-arm
            target: editor
            arch: arm64
            build-mono: true
            tests: true
            bin: "./bin/godot.macos.editor.arm64.mono"

          - name: Template (target=template_release)
            cache-name: macos-template
            target: template_release
            tests: false
            sconsflags: debug_symbols=no

    steps:
      - uses: actions/checkout@v4

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Set up .NET Sdk
        uses: actions/setup-dotnet@v3
        if: ${{ matrix.build-mono }}
        with:
          dotnet-version: '6.0.x'
        
      - name: Setup Vulkan SDK
        run: |
          sh misc/scripts/install_vulkan_sdk_macos.sh

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: macos
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          build-mono: ${{ matrix.build-mono }}
          tests: ${{ matrix.tests }}

      - name: Generate C# glue
        if: ${{ matrix.build-mono }}
        run: |
          ${{ matrix.bin }} --headless --generate-mono-glue ./modules/mono/glue

      - name: Build .NET solutions
        if: ${{ matrix.build-mono }}
        run: |
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=macos

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}

      # Execute unit tests for the editor
      - name: Unit tests
        if: ${{ matrix.tests }}
        run: |
          ${{ matrix.bin }} --version
          ${{ matrix.bin }} --help
          ${{ matrix.bin }} --test --force-colors
